In [2]:
import torch

In [4]:
!pip install gpytorch

     |████████████████████████████████| 276kB 2.7MB/s 
  Created wheel for gpytorch: filename=gpytorch-1.2.0-py2.py3-none-any.whl size=459510 sha256=a8b1fd2f6d10e67dc92ba27cac3ed6d5c78d3b5a57376433d8633321ecc14af9
  Stored in directory: /root/.cache/pip/wheels/e8/eb/36/f415815e8a8b66c1f1d5a3534718c39c2d83501051f1ab604e
Successfully built gpytorch


In [ ]:
x=5
print(x)

5


In [3]:
a = torch.empty(5, 7, dtype=torch.float)

In [ ]:
print(a)

tensor([[2.4898e-36, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00]])


In [5]:
a = torch.randn(5, 7, dtype=torch.double)
print(a)
print(a.size())

tensor([[-0.9307,  0.0591,  1.9318, -0.5151, -0.0478,  1.3850,  1.3112],
        [-2.0459, -0.1369,  1.5296, -0.6615, -0.6916,  0.9625,  0.4747],
        [-0.2460,  0.8230,  1.2171,  0.7871,  0.0869, -0.1864,  0.4002],
        [-0.2316,  1.4442, -0.0954, -0.7905,  1.0166, -1.5203,  1.4065],
        [ 0.1348,  1.6787, -0.7519,  0.3652,  0.5576, -0.4399, -0.0858]],
       dtype=torch.float64)
torch.Size([5, 7])


# Inplace / Out-of-place
The first difference is that ALL operations on the tensor that operate in-place on it will have an _ postfix. For example, add is the out-of-place version, and add_ is the in-place version.

In [6]:
a.fill_(3.5)
# a has now been filled with the value 3.5

b = a.add(4.0)
# a is still filled with 3.5
# new tensor b is returned with values 3.5 + 4.0 = 7.5

print(a, b)

tensor([[3.5000, 3.5000, 3.5000, 3.5000, 3.5000, 3.5000, 3.5000],
        [3.5000, 3.5000, 3.5000, 3.5000, 3.5000, 3.5000, 3.5000],
        [3.5000, 3.5000, 3.5000, 3.5000, 3.5000, 3.5000, 3.5000],
        [3.5000, 3.5000, 3.5000, 3.5000, 3.5000, 3.5000, 3.5000],
        [3.5000, 3.5000, 3.5000, 3.5000, 3.5000, 3.5000, 3.5000]],
       dtype=torch.float64) tensor([[7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000],
        [7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000],
        [7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000],
        [7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000],
        [7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000]],
       dtype=torch.float64)


# Zero Indexing

In [7]:
b = a[0, 3]  # select 1st row, 4th column from a
print(b)

tensor(3.5000, dtype=torch.float64)


In [8]:
b = a[:, 3:5]  # selects all rows, 4th column and  5th column from a
print(b)

tensor([[3.5000, 3.5000],
        [3.5000, 3.5000],
        [3.5000, 3.5000],
        [3.5000, 3.5000],
        [3.5000, 3.5000]], dtype=torch.float64)


# Creating Tensors

In [9]:
x = torch.ones(5, 5)
print(x)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


In [10]:
z = torch.empty(5, 2)
z[:, 0] = 10
z[:, 1] = 100
print(z)

tensor([[ 10., 100.],
        [ 10., 100.],
        [ 10., 100.],
        [ 10., 100.],
        [ 10., 100.]])


# Numpy Bridge
Converting a torch Tensor to a numpy array and vice versa is a breeze. The torch Tensor and numpy array will share their underlying memory locations, and changing one will change the other.

In [11]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [12]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [13]:
a.add_(1)
print(a)
print(b)    # see how the numpy array changed in value

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


## Converting numpy Array to torch Tensor

In [14]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)  # see how changing the np array changed the torch Tensor automatically

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# CUDA Tensors
CUDA Tensors are nice and easy in pytorch, and transfering a CUDA tensor from the CPU to GPU will retain its underlying type.

In [15]:
# let us run this cell only if CUDA is available
a = torch.ones(1,10)
if torch.cuda.is_available():

    # creates a LongTensor and transfers it
    # to GPU as torch.cuda.LongTensor
    a = torch.ones((10,), device=torch.device("cuda"))
    print(type(a))
    b = a.to(torch.device("cpu"))
    # transfers it to CPU, back to
    # being a torch.LongTensor

<class 'torch.Tensor'>


In [16]:
a

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], device='cuda:0')

In [17]:
b

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])