## topics

* tensor (un)squeezing
* random tensors

### squeeze and unsqueeze

* we use batches for learning, but we have to tell pytorch
* batches are tensors with size 1,n, m where n=number of examples and m=number of features


* we use squeeze and unsqueeze to convert (add or remove dimension of size 1, mostly)

In [1]:
import torch
import torch.nn as nn

x = torch.tensor([1, 2, 3, 4])

print(x)
# add a dimension with size 1 at 0
y=torch.unsqueeze(x, 0)
y

tensor([1, 2, 3, 4])


tensor([[1, 2, 3, 4]])

In [2]:
z=torch.unsqueeze(x, 1)
z

tensor([[1],
        [2],
        [3],
        [4]])

In [3]:
u=torch.unsqueeze(z,0)    # a batch with 4 examples (only 1 feature per example)
u

tensor([[[1],
         [2],
         [3],
         [4]]])

In [4]:
# and the other way round ....

torch.squeeze(u, 0)

tensor([[1],
        [2],
        [3],
        [4]])

In [5]:
u.size()

torch.Size([1, 4, 1])

In [6]:
torch.randn(1, 1, 2)

tensor([[[-0.2686,  1.0312]]])

### torch.randn for random input

input = torch.randn(1, 1, 2)    

torch.randn(seq_len, batch_size, inputlen)

In [7]:
# a batch with one example and one feature

torch.randn(1, 1, 1)

tensor([[[0.7437]]])

In [8]:
# a batch with one example, but 2 features
torch.randn(1, 1, 2)

tensor([[[-0.4312,  0.9205]]])

In [10]:
# a batch with 2 examples

torch.randn(2, 2, 1)

tensor([[[-1.9892],
         [-0.3857]],

        [[ 1.4250],
         [ 0.3898]]])

In [11]:
# not a batch

torch.randn(1, 2)

tensor([[0.9958, 0.0969]])

In [12]:
# a batch with a single example  dim=0 or dim=1: same effect

torch.unsqueeze(torch.rand(1,2),0)

tensor([[[0.8258, 0.1301]]])

In [13]:
# a batch with 2 examples

torch.unsqueeze(torch.rand(1,2),2)

tensor([[[0.6111],
         [0.5436]]])

In [14]:
x=torch.randn(1, 2, 1)

raw_weights = torch.bmm(x, x.transpose(1, 2))

print(x)
print(x.transpose(1,2)) 

raw_weights

tensor([[[-1.4626],
         [-0.9059]]])
tensor([[[-1.4626, -0.9059]]])


tensor([[[2.1392, 1.3249],
         [1.3249, 0.8206]]])

In [15]:
import torch.nn.functional as F

weights = F.softmax(raw_weights, dim=2)

weights

tensor([[[0.6930, 0.3070],
         [0.6235, 0.3765]]])