In [1]:
import numpy as np

x1 = np.array([0.95, 0.89, .92, 0.98, 0.88, 0.975, 0.90, 0.98, 0.98, 0.94])
x2 = np.array([0.85, 0.95, .88, 0.91, 0.94, 0.92, 0.955, 0.89, 0.82, 0.85])

diff = np.subtract(x1,x2)
diff

array([ 0.1  , -0.06 ,  0.04 ,  0.07 , -0.06 ,  0.055, -0.055,  0.09 ,
        0.16 ,  0.09 ])

In [4]:
mean_diff = np.mean(diff)
print(mean_diff)
sd = np.std(diff)
std_err = sd/np.sqrt(len(x1))
print(std_err)

0.043000000000000003
0.023034756347745457


In [3]:
t_val = mean_diff / std_err
t_val

1.8667442950491056

In [ ]:
len(x1)

In [ ]:
print("conf level 95% df 9: P=1.833")
print("conf level 99% df 9: P=2.821")

In [6]:
import torch
import torch.nn.functional as F

input = torch.randn(10, 30, 60)
x1 = F.max_pool2d(input, kernel_size=(2,2))
x2 = F.max_pool2d(input, kernel_size=(3,1))
x3 = F.avg_pool2d(input, kernel_size=(1,3))
x4 = F.avg_pool2d(input, kernel_size=(2,3))

#in general: reduces the dimensionality
#kernel_size – the size of the window to take a max over
#stride – the stride of the window. Default value is kernel_size
# -> used to reduce computational load and overfitting

In [7]:
print(x1.shape)
print(x2.shape)
print(x3.shape)
print(x4.shape)

torch.Size([10, 15, 30])
torch.Size([10, 10, 60])
torch.Size([10, 30, 20])
torch.Size([10, 15, 20])


In [8]:
input = torch.tensor([[[2., 1., 1., 2.], [0., 0., 2., 0.], [0., 2., 2., 1.], [0., 2., 0., 1.]]])
input.shape

torch.Size([1, 4, 4])

In [9]:
output_max = F.max_pool2d(input, kernel_size=(2,2))
output_avg = F.avg_pool2d(input, kernel_size=(2,2))

In [10]:
print(output_max)
print(output_avg)

tensor([[[2., 2.],
         [2., 2.]]])
tensor([[[0.7500, 1.2500],
         [1.0000, 1.0000]]])
